---
- hosts: localhost
  vars:
    helm_chart_url: "https://argoproj.github.io/argo-helm"
    helm_release_name: "argo-cd"
  tasks:
    - name: Helm repo add
      kubernetes.core.helm_repository:
        name: "{{ helm_release_name }}"
        repo_url: "{{ helm_chart_url }}"
        
    - name: create namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ helm_release_name }}"

    - name: helm install argo-CD
      kubernetes.core.helm:
        name: "{{ helm_release_name }}"
        namespace: "{{ helm_release_name }}"
        chart_ref: "{{ helm_release_name }}/argo-cd"
